name: Mutation Tests Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run test:mutation
      - name: Archive mutation coverage results
        uses: actions/upload-artifact@v1
        with:
          name: mutation-report
          path: ./reports/mutation
